version: '3.8'

services:
  backend:
    image: karthiq18/backend:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${RDS_HOST}
      DB_USER: ${RDS_USER}
      DB_PASSWORD: ${RDS_PASSWORD}

  frontend:
    image: karthiq18/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend